# Basic Kodelet Action Workflow
#
# This example shows the minimal configuration needed to use Kodelet Action
# for automated issue resolution and PR responses.
#
# Setup:
# 1. Add ANTHROPIC_API_KEY to your repository secrets
# 2. Copy this file to .github/workflows/kodelet.yml in your repository
# 3. Comment "@kodelet" on issues or PRs to trigger automation

name: Background Kodelet

on:
  issue_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review_comment:
    types: [created]
  pull_request_review:
    types: [submitted]

permissions:
  issues: write          # Comment on issues
  pull-requests: write   # Comment on PRs and create PRs
  contents: write        # Push commits and create branches

jobs:
  background-agent:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # 6 hours max execution time

    if: |
      (
        (github.event_name == 'issues' && contains(github.event.issue.body, '@kodelet')) ||
        (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@kodelet')) ||
        (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@kodelet')) ||
        (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@kodelet'))
      ) &&
      (
        (github.event.issue.author_association == 'OWNER' || github.event.issue.author_association == 'MEMBER' || github.event.issue.author_association == 'COLLABORATOR') ||
        (github.event.comment.author_association == 'OWNER' || github.event.comment.author_association == 'MEMBER' || github.event.comment.author_association == 'COLLABORATOR') ||
        (github.event.review.author_association == 'OWNER' || github.event.review.author_association == 'MEMBER' || github.event.review.author_association == 'COLLABORATOR')
      )

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full clone for proper git operations
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Kodelet
        uses: jingkaihe/kodelet-action@v1
        with:
          anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
          # All other inputs are automatically populated from GitHub context
          # You can override them if needed:
          # commenter: custom-user
          # event-name: issue_comment
          # issue-number: 123
          # comment-id: 456
          # repository: owner/repo
          # is-pr: false
          # pr-number: 789
          # kodelet-version: latest
